### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by johnwyles** [Jerajo/activate-killer-instinct-mode#4]
I tried going through the coffeescript but it isn't my language not to mention it's compiled and not to mention I don't know what the heck is going on in all the path crap but needless to say I get the following issues with the playing of the WAV files:

```
/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds//Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/Level%20Up.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
```

As you can see this file is the concatenation of the current modules path along with the actual path to the WAV file for some reason.  The other two issues I also see are:

```
/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/ Failed to load resource: net::ERR_FILE_NOT_FOUND
/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds//Users/johnwyles/.wav Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
```

Where you can see that the modules directory is the path in the first case and then the users home directory only with a `""` blank WAV file is set.

**Comment by Jerajo** [comment]
what version of atom do you have?

**Comment by johnwyles** [comment]
`1.32.2`

**Comment by Jerajo** [comment]
That's weird. Did you try to uninstall it and install it again with the atom package manager?
It seems that it is an installation error. Try with this command and tell me.

```console
apm install activate-killer-instinct-mode
```

**Comment by johnwyles** [comment]
```
Uncaught Error: ENOENT: no such file or directory, scandir '\Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/'

fs.js:904
Hide Stack Trace
Error: ENOENT: no such file or directory, scandir '\Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:608:28)
    at Object.getAudioFiles (/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/lib/play-exclamation.coffee:59:19)
    at Object.enable (/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/lib/play-exclamation.coffee:14:20)
    at Object.setup (/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/lib/killer-instinct.coffee:31:18)
    at Object.enable (/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/lib/killer-instinct.coffee:21:6)
    at /Users/johnwyles/.atom/packages/activate-power-mode/lib/plugin-registry.coffee:79:18
    at Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332465)
    at Config.observe (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:326976)
    at Object.observePlugin (/Users/johnwyles/.atom/packages/activate-power-mode/lib/plugin-registry.coffee:76:46)
    at Object.enable (/Users/johnwyles/.atom/packages/activate-power-mode/lib/plugin-registry.coffee:26:8)
    at Object.enable (/Users/johnwyles/.atom/packages/activate-power-mode/lib/plugin-manager.coffee:71:21)
    at Object.enable (/Users/johnwyles/.atom/packages/activate-power-mode/lib/power-editor.coffee:7:20)
    at Object.enable (/Users/johnwyles/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:43:18)
    at Object.toggle (/Users/johnwyles/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:39:38)
    at /Users/johnwyles/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:28:10
```

**Comment by johnwyles** [comment]
```
The error was thrown from the activate-killer-instinct-mode package. Atom is out of date: 1.32.2 installed; 1.33.0 latest. Upgrading to the latest version may fix this issue.
```

**Comment by johnwyles** [comment]
After upgrade to `1.33.0`, as you would expect, is now:
```
The error was thrown from the activate-killer-instinct-mode package. You can help by creating an issue. Please explain what actions triggered this error.
```

**Comment by johnwyles** [comment]
if I had to guess I would think it could be here in `config-observers.coffee`:

```
    @pathObserver = atom.config.observe 'activate-killer-instinct-mode.customExclamations.path', (value) =>
      if value is "../sounds/"
        @conf['path'] = path.join(__dirname, value)
      else
        if value[value.length-1] isnt '/' and value[value.length-1] isnt '\\'
          @conf['path'] = value + '\\'
        else if value[value.length-1] is '/'
          @conf['path'] = value.replace('/','\\')
        else @conf['path'] = value
```

**Comment by Jerajo** [comment]
I see that the path is not completed. It doesn't start with the letter C: 
`'\Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/'`

For examaple: 
`C:\Users\jerajo\.atom\packages\activate-killer-instinct-mode\sounds`

Fist try to go to the path and see if the folder is empty. If It isn't, try to paste the full path on the package config.

![imagen](https://user-images.githubusercontent.com/26252994/49412813-2bd4c000-f744-11e8-920c-9d671fdd71ad.png)

**Comment by johnwyles** [comment]
ah, I am on a Mac - you may check other plugins and how they handle this - I will try this in an hour or so when I am back on the machin with a `/` or something to make that work

**Comment by Jerajo** [comment]
As you can see, atom uses Node.Js
and modules to read the files and routes.

```js
path = require 'path'
fs = require 'fs'

@conf['path'] = path.join(__dirname, "../sounds/")

if fs.existsSync(@conf['path'])
allFiles = fs.readdirSync(@conf['path'])
```

More information [here](https://stackoverflow.com/questions/32705219/nodejs-accessing-file-with-relative-path).

Ivent with the full path does not work?.

**Comment by johnwyles** [comment]
I am not directing this at you but might see why your code is the only plugin not working - I have a ton of them installed. How are you loading files or paths differently than other plugins, if you are, and why would that break? I will try providing the full path in an hour or so and mess with it - would love to learn along with you.

**Comment by Jerajo** [comment]
> 
> 
> ah, I am on a Mac - you may check other plugins and how they handle this - I will try this in an hour or so when I am back on the machin with a `/` or something to make that work

Ok I do not have a mac I think that you can make **PR** with a condition to verify if is mac or windows, and change the path according to the operative system. The config is handled [here](https://github.com/Jerajo/activate-killer-instinct-mode/blob/master/lib/config-observers.coffee).

**Comment by Jerajo** [comment]
I currently believe that the problem is on line 31 with **__dirname**.

https://github.com/Jerajo/activate-killer-instinct-mode/blob/83c6f05f3986c955a1db4178645bfd8797fd1a3c/lib/config-observers.coffee#L31

**Comment by johnwyles** [comment]
Found the issue:

```
config-observers.coffee? [sm]:30 FOO /Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/
config-observers.coffee? [sm]:37 FOO2 undefined
config-observers.coffee? [sm]:39 FOO3 \Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/
```

in `config-observer.coffee`:
```
    @pathObserver = atom.config.observe 'activate-killer-instinct-mode.customExclamations.path', (value) =>
      console.log "FOO " + value
      if value is "../sounds/"
        @conf['path'] = path.join(__dirname, value)
      else
        if value[value.length-1] isnt '/' and value[value.length-1] isnt '\\'
          @conf['path'] = value + '\\'
        else if value[value.length-1] is '/'
          console.log "FOO2 " + @conf['path']
          @conf['path'] = value.replace('/','\\')
          console.log "FOO3 " + @conf['path']
```

**Comment by johnwyles** [comment]
After removing that whole `else if` there are even more problems I do not have time to dig around with. Now at least the plugin is loading but it is playing this file somehow:
`file:///Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds//Users/johnwyles/.wav`

**Comment by Jerajo** [comment]
If you can see the package verify if you has the defoult confing wicht is "../sounds/" in that case it will join the path with your __dirname.

https://github.com/Jerajo/activate-killer-instinct-mode/blob/83c6f05f3986c955a1db4178645bfd8797fd1a3c/lib/config-observers.coffee#L29-L31

More info about Node.js and Mac [here](https://jaketrent.com/post/paths-in-node/).

**Comment by Jerajo** [comment]
@johnwyles Check if with the last commit [120e160a6efd37a47baa364008c64ce969e5065d] your issue has been solved.

Before I upload the new release

**Comment by johnwyles** [comment]
I checked out this git hash / branch in my packages folder.

I toggled Activate Powermode plugin off. Toggled it on. Toggled the Killer Instinct plugin off (within Activate PowerMode settings). Toggled the Killer Instinct plugin on (within Activate PowerMode settings). Here is the Developer Console output from Atom:

```audio-player.coffee? [sm]:55 Uncaught (in promise) DOMException: The element has no supported sources.
play @ audio-player.coffee? [sm]:55
module.exports.Api.playAudio @ api.coffee? [sm]:12
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235
onInput @ play-audio.coffee? [sm]:12
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
Promise (async)
play @ audio-player.coffee? [sm]:55
module.exports.Api.playAudio @ api.coffee? [sm]:12
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235
onInput @ play-audio.coffee? [sm]:12
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
requestIdleCallback (async)
handleInput @ power-editor.coffee? [sm]:46
simpleDispatch @ VM22 <embedded>:11
emit @ VM22 <embedded>:11
emitDidChangeTextEvent @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
mergeIntersectingSelections @ VM22 <embedded>:11
mergeSelections @ VM22 <embedded>:11
mergeIntersectingSelections @ VM22 <embedded>:11
mutateSelectedText @ VM22 <embedded>:11
insertText @ VM22 <embedded>:11
e.(anonymous function) @ VM22 <embedded>:11
didTextInput @ VM22 <embedded>:11
audio-player.coffee? [sm]:55 Uncaught (in promise) DOMException: The element has no supported sources.
play @ audio-player.coffee? [sm]:55
module.exports.Api.playAudio @ api.coffee? [sm]:12
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235
onInput @ play-audio.coffee? [sm]:12
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
Promise (async)
play @ audio-player.coffee? [sm]:55
module.exports.Api.playAudio @ api.coffee? [sm]:12
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235
onInput @ play-audio.coffee? [sm]:12
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
requestIdleCallback (async)
handleInput @ power-editor.coffee? [sm]:46
simpleDispatch @ VM22 <embedded>:11
emit @ VM22 <embedded>:11
emitDidChangeTextEvent @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
mergeIntersectingSelections @ VM22 <embedded>:11
mergeSelections @ VM22 <embedded>:11
mergeIntersectingSelections @ VM22 <embedded>:11
mutateSelectedText @ VM22 <embedded>:11
insertText @ VM22 <embedded>:11
e.(anonymous function) @ VM22 <embedded>:11
didTextInput @ VM22 <embedded>:11
/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/:1 GET file:///Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/ net::ERR_FILE_NOT_FOUND
/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds//Users/johnwyles/.wav:1 GET file:///Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds//Users/johnwyles/.wav net::ERR_FILE_NOT_FOUND
index.html:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
Promise (async)
play @ play-exclamation.coffee? [sm]:50
onComboEndStreak @ killer-instinct.coffee? [sm]:96
(anonymous) @ plugin-manager.coffee? [sm]:120
onEnabled @ plugin-registry.coffee? [sm]:92
runOnComboEndStreak @ plugin-manager.coffee? [sm]:119
endStreak @ combo-renderer.coffee? [sm]:172
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:160
trailingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:207
timerExpired @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:195
setTimeout (async)
timerExpired @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:198
setTimeout (async)
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:168
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:235
modifyStreak @ combo-renderer.coffee? [sm]:102
onInput @ combo-mode.coffee? [sm]:28
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
requestIdleCallback (async)
handleInput @ power-editor.coffee? [sm]:46
simpleDispatch @ VM22 <embedded>:11
emit @ VM22 <embedded>:11
emitDidChangeTextEvent @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
mergeIntersectingSelections @ VM22 <embedded>:11
mergeSelections @ VM22 <embedded>:11
mergeIntersectingSelections @ VM22 <embedded>:11
mutateSelectedText @ VM22 <embedded>:11
insertText @ VM22 <embedded>:11
e.(anonymous function) @ VM22 <embedded>:11
didTextInput @ VM22 <embedded>:11
audio-player.coffee? [sm]:55 Uncaught (in promise) DOMException: The element has no supported sources.
play @ audio-player.coffee? [sm]:55
module.exports.Api.playAudio @ api.coffee? [sm]:12
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235
onInput @ play-audio.coffee? [sm]:12
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
Promise (async)
play @ audio-player.coffee? [sm]:55
module.exports.Api.playAudio @ api.coffee? [sm]:12
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235
onInput @ play-audio.coffee? [sm]:12
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
requestIdleCallback (async)
handleInput @ power-editor.coffee? [sm]:46
simpleDispatch @ VM22 <embedded>:11
emit @ VM22 <embedded>:11
emitDidChangeTextEvent @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
s.(anonymous function) @ VM22 <embedded>:11
handleCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.dispatchCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.handleKeyboardEvent @ VM22 <embedded>:11
handleDocumentKeyEvent @ VM22 <embedded>:11
audio-player.coffee? [sm]:55 Uncaught (in promise) DOMException: The element has no supported sources.
play @ audio-player.coffee? [sm]:55
module.exports.Api.playAudio @ api.coffee? [sm]:12
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235
onInput @ play-audio.coffee? [sm]:12
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
Promise (async)
play @ audio-player.coffee? [sm]:55
module.exports.Api.playAudio @ api.coffee? [sm]:12
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235
onInput @ play-audio.coffee? [sm]:12
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
requestIdleCallback (async)
handleInput @ power-editor.coffee? [sm]:46
simpleDispatch @ VM22 <embedded>:11
emit @ VM22 <embedded>:11
emitDidChangeTextEvent @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
s.(anonymous function) @ VM22 <embedded>:11
handleCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.dispatchCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.handleKeyboardEvent @ VM22 <embedded>:11
handleDocumentKeyEvent @ VM22 <embedded>:11
audio-player.coffee? [sm]:55 Uncaught (in promise) DOMException: The element has no supported sources.
play @ audio-player.coffee? [sm]:55
module.exports.Api.playAudio @ api.coffee? [sm]:12
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235
onInput @ play-audio.coffee? [sm]:12
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
Promise (async)
play @ audio-player.coffee? [sm]:55
module.exports.Api.playAudio @ api.coffee? [sm]:12
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:160
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:170
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:235
onInput @ play-audio.coffee? [sm]:12
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
requestIdleCallback (async)
handleInput @ power-editor.coffee? [sm]:46
simpleDispatch @ VM22 <embedded>:11
emit @ VM22 <embedded>:11
emitDidChangeTextEvent @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
s.(anonymous function) @ VM22 <embedded>:11
handleCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.dispatchCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.handleKeyboardEvent @ VM22 <embedded>:11
handleDocumentKeyEvent @ VM22 <embedded>:11
/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/:1 GET file:///Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds/ net::ERR_FILE_NOT_FOUND
/Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds//Users/johnwyles/.wav:1 GET file:///Users/johnwyles/.atom/packages/activate-killer-instinct-mode/sounds//Users/johnwyles/.wav net::ERR_FILE_NOT_FOUND
index.html:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
Promise (async)
play @ play-exclamation.coffee? [sm]:50
onComboEndStreak @ killer-instinct.coffee? [sm]:96
(anonymous) @ plugin-manager.coffee? [sm]:120
onEnabled @ plugin-registry.coffee? [sm]:92
runOnComboEndStreak @ plugin-manager.coffee? [sm]:119
endStreak @ combo-renderer.coffee? [sm]:172
invokeFunc @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:160
trailingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:207
timerExpired @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:195
setTimeout (async)
timerExpired @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:198
setTimeout (async)
leadingEdge @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:168
debounced @ /Users/johnwyles/.atom/packages/activate-power-mode/node_modules/lodash.debounce/index.js:235
modifyStreak @ combo-renderer.coffee? [sm]:102
onInput @ combo-mode.coffee? [sm]:28
(anonymous) @ plugin-manager.coffee? [sm]:105
onEnabled @ plugin-registry.coffee? [sm]:92
runOnInput @ plugin-manager.coffee? [sm]:102
(anonymous) @ power-editor.coffee? [sm]:55
requestIdleCallback (async)
handleInput @ power-editor.coffee? [sm]:46
simpleDispatch @ VM22 <embedded>:11
emit @ VM22 <embedded>:11
emitDidChangeTextEvent @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
transact @ VM22 <embedded>:11
s.(anonymous function) @ VM22 <embedded>:11
handleCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.dispatchCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.handleKeyboardEvent @ VM22 <embedded>:11
handleDocumentKeyEvent @ VM22 <embedded>:11```

**Comment by johnwyles** [comment]
(the stack traces are easier to see if you search for "Uncaught" in your browser and then every subsequent line until you see the next "Uncaught" is highlighted)

**Comment by Jerajo** [comment]
Did you install the package dependencies with npm?

Open the console in your repo directory and type. 

```console
    npm install
```

And tell me if the path issue persists.

**Comment by johnwyles** [comment]
I was coming back to comment that when I did an `npm install lodash lodash.debounce` it works now

**Comment by johnwyles** [comment]
I did not get those node modules installed after closing/opening Atom but I presume there is a reason for that that you know. Your fix is good! Thanks for the all the help man! I learned something and you were able to fix the bug in your code! Fun adventure :)

**Comment by Jerajo** [comment]
Ok, I going to publish the new release.
